name: "Protocol Buffer Go Stubs Generation"
on:
  push:

    tags:
      - proto/v**
jobs:
  protoc:
    name: "Generate"
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v1
      - name: Extract Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/proto/}" >> $GITHUB_ENV
      - name: "Generate for Golang"
        run: |
          cd ${GITHUB_WORKSPACE}/proto
          make setup
          make run RELEASE_VERSION=${{ env.RELEASE_VERSION }}
